version: '3.7'

#services:
#  locust:
#    build: .
#    command: /bin/sh
#    volumes:
#      - ./:/usr/src/locust
#    ports:
#      - 8089:8089
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t


services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master


