# Generated by Django 3.0.8 on 2021-11-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='ticket',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='competition.QueueTicket'),
        ),
    ]
