# Generated by Django 3.0.8 on 2024-10-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20211107_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_raining', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='lap',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laps', to='competition.Runner'),
        ),
    ]
