# Generated by Django 3.0.8 on 2024-10-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_lap_raining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='raining',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
