# Generated by Django 3.0.8 on 2024-10-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20241019_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='raining',
            field=models.BooleanField(default=False),
        ),
    ]
